# docker-compose.yml version to use 
version: '3.9'


# define services, so Flask-Web-App can run
services:
  web:     # service name
    build: .  # use Dockerfile in current directory to build image
    ports:
      - "5000:5000" # container port:host port connect
    volumes:
      - .:/app  # connect local Project directory to container directory /app, BIND 
    environment: # set environment variables
    - FLASK_ENV=development
